apiVersion: v1
kind: Service
metadata:
  name: video-feed-provider
  namespace: short-stream
spec:
  selector:
    app: video-feed-provider
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
