apiVersion: v1
kind: Service
metadata:
  name: video-conversor
  namespace: short-stream
spec:
  selector:
    app: video-conversor
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
