apiVersion: v1
kind: Service
metadata:
  name: video-metadata-service
  namespace: short-stream
spec:
  selector:
    app: video-metadata-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
