apiVersion: v1
kind: Namespace
metadata:
  name: short-stream
  labels:
    app.kubernetes.io/name: short-stream
    app.kubernetes.io/instance: short-stream
    app.kubernetes.io/version: v1
    app.kubernetes.io/part-of: short-stream
    app.kubernetes.io/managed-by: short-stream
